# set custom network name
# https://forums.docker.com/t/set-default-network-name-for-compose/36779

version: '3.6'

services:
  webinterface:
    image: webinterface
    container_name: webinterface
    build:
      context: ./WebInterface
      dockerfile: Dockerfile
#    environment:
#      - DOTNET_USE_POLLING_FILE_WATCHER=1

#    networks:
#      - iiasa
#    external_links:
#      - geonode_geonode_1
    ports:
      - "5000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webinterface_default

networks:
  webinterface_default:

#networks:
#  default:
#    name: "iiasa_default"
#  default:
#    external: 
#      name: geonode_default